
const directory= [
    {
        name:"Downloads",
        permissions:"",
        path: "/home/user",
        link:2,
        user: "",
        group: "",
        size: 0,
        time:"",
    },
    {
        name:"Documents",
        permissions:"",
        path: "/home/user",
        link:2,
        user: "",
        group: "",
        size: 4,
        time:"",
    },
    {
        name:"Desktop",
        permissions:"",
        path: "/home/user",
        link:2,
        user: "",
        group: "",
        size: 0,
        time:"",
    },
    {
        name:"Music",
        permissions:"",
        path: "/home/user",
        link:2,
        user: "",
        group: "",
        size: 10,
        time:"",
    },
    {
        name:"Pictures",
        permissions:"",
        path: "/home/user",
        link:2,
        user: "",
        group: "",
        size: 0,
        time:"",
    },
    {
        name:"Public",
        permissions:"",
        path: "/home/user",
        link:2,
        user: "",
        group: "",
        size: 0,
        time:"",
    },
    {
        name:"Pictures",
        permissions:"",
        path: "/home/user",
        link:2,
        user: "",
        group: "",
        size: 3,
        time:"",
    },
    {
        name:"Videos",
        permissions:"",
        path: "/home/user",
        link:2,
        user: "",
        group: "",
        size: 50,
        time:"",
    },
    {
        name:"user",
        permissions:"",
        path: "/home",
        link:2,
        user: "",
        group: "",
        size: 0,
        time:"",
    },
    {
        name:"home",
        permissions:"",
        path: "/",
        link:2,
        user: "",
        group: "",
        size: 123,
        time:"",
    },
    {
        name:"bin",
        permissions:"",
        path: "/",
        link:2,
        user: "",
        group: "",
        size: 0,
        time:"",
    },
    {
        name:"boot",
        permissions:"",
        path: "/",
        link:2,
        user: "",
        group: "",
        size: 1,
        time:"",
    },
    {
        name:"dev",
        permissions:"",
        path: "/",
        link:2,
        user: "",
        group: "",
        size: 30,
        time:"",
    },
    {
        name:"etc",
        permissions:"",
        path: "/",
        link:2,
        user: "",
        group: "",
        size: 0,
        time:"",
    },
    {
        name:"lib",
        permissions:"",
        path: "/",
        link:2,
        user: "",
        group: "",
        size: 2,
        time:"",
    },
    {
        name:"proc",
        permissions:"",
        path: "/",
        link:2,
        user: "",
        group: "",
        size: 0,
        time:"",
    },
    {
        name:"root",
        permissions:"",
        path: "/",
        link:2,
        user: "",
        group: "",
        size: 19,
        time:"",
    },
    {
        name:"run",
        permissions:"",
        path: "/",
        link:2,
        user: "",
        group: "",
        size: 0,
        time:"",
    },
    {
        name:"sbin",
        permissions:"",
        path: "/",
        link:2,
        user: "",
        group: "",
        size: 0,
        time:"",
    },
    {
        name:"srv",
        permissions:"",
        path: "/",
        link:2,
        user: "",
        group: "",
        size: 39,
        time:"",
    },
    {
        name:"sys",
        permissions:"",
        path: "/",
        link:2,
        user: "",
        group: "",
        size: 2,
        time:"",
    },
    {
        name:"tmp",
        permissions:"",
        path: "/",
        link:2,
        user: "",
        group: "",
        size: 0,
        time:"",
    },
    {
        name:"usr",
        permissions:"",
        path: "/",
        link:2,
        user: "",
        group: "",
        size: 4,
        time:"",
    },
    {
        name:"var",
        permissions:"",
        path: "/",
        link:2,
        user: "",
        group: "",
        size: 80,
        time:"",
    },
]

export default directory