
const directory = [
    {
        name: ".",
        permissions: "drwx------",
        path: "/home/",
        link: 22,
        user: "",
        group: "",
        size: 4096,
        time: "Aug  7 10:51",
    },
    {
        name: "..",
        permissions: "drwxr-xr-x",
        path: "/home/",
        link: 3,
        user: "root",
        group: "root",
        size: 4096,
        time: "Jul 31 22:29",
    },
    {
        name: "Desktop",
        permissions: "drwxr-xr-x",
        path: "/home/",
        link: 2,
        user: "",
        group: "",
        size: 4096,
        time: "Aug  6 00:01",
    },
    {
        name: "Documents",
        permissions: "drwxr-xr-x",
        path: "/home/",
        link: 2,
        user: "",
        group: "",
        size: 4096,
        time: "Aug  1 00:23",
    },
    {
        name: "Downloads",
        permissions: "drwxr-xr-x",
        path: "/home/",
        link: 2,
        user: "",
        group: "",
        size: 4096,
        time: "Jul 31 22:33",
    },
    {
        name: "Music",
        permissions: "drwxr-xr-x",
        path: "/home/",
        link: 2,
        user: "",
        group: "",
        size: 4096,
        time: "Jul 31 22:33",
    },
    {
        name: "Pictures",
        permissions: "drwxr-xr-x",
        path: "/home/",
        link: 2,
        user: "",
        group: "",
        size: 4096,
        time: "Jul 31 22:33",
    },
    {
        name: "Public",
        permissions: "drwxr-xr-x",
        path: "/home/",
        link: 2,
        user: "",
        group: "",
        size: 4096,
        time: "Jul 31 22:33",
    },
    {
        name: "Templates",
        permissions: "drwxr-xr-x",
        path: "/home/",
        link: 2,
        user: "",
        group: "",
        size: 4096,
        time: "Jul 31 22:33",
    },
    {
        name: "Videos",
        permissions: "drwxr-xr-x",
        path: "/home/",
        link: 2,
        user: "",
        group: "",
        size: 4096,
        time: "Jul 31 22:33",
    },
    {
        name: ".cache",
        permissions: "drwxr-xr-x",
        path: "/home/",
        text: "",
        link: 14,
        user: "",
        group: "",
        size: 4096,
        time: "Aug  1 01:48",
    },
    {
        name: ".config",
        permissions: "drwxr-xr-x",
        path: "/home/",
        text: "",
        link: 17,
        user: "",
        group: "",
        size: 4096,
        time: "Aug  5 16:38",
    },
    {
        name: "user",
        permissions: "drwx------",
        path: "/home",
        link: 14,
        user: "",
        group: "",
        size: 4096,
        time: "",
    },
    {
        name: ".",
        permissions: "drwxr-xr-x",
        path: "/home",
        link: 3,
        user: "root",
        group: "root",
        size: 4096,
        time: "Jul 31 22:29",
    },
    {
        name: "..",
        permissions: "drwxr-xr-x",
        path: "/home",
        link: 17,
        user: "root",
        group: "root",
        size: 4096,
        time: "Jul 29 14:09",
    },
    {
        name: "home",
        permissions: "drwxr-xr-x",
        path: "/",
        link: 3,
        user: "root",
        group: "root",
        size: 4096,
        time: "Jul 31 22:29",
    },
    {
        name: "bin",
        permissions: "lrwxrwxrwx",
        path: "/",
        link: 1,
        user: "root",
        group: "root",
        size: 9,
        time: "Jun  9 09:53",
    },
    {
        name: "boot",
        permissions: "drwxr-xr-x",
        path: "/",
        link: 5,
        user: "root",
        group: "root",
        size: 4096,
        time: "Jul 31 22:32",
    },
    {
        name: "dev",
        permissions: "drwxr-xr-x",
        path: "/",
        link: 19,
        user: "root",
        group: "root",
        size: 4200,
        time: "Aug  7 10:31",
    },
    {
        name: "etc",
        permissions: "drwxr-xr-x",
        path: "/",
        link: 106,
        user: "root",
        group: "root",
        size: 4096,
        time: "Aug  7 10:31",
    },
    {
        name: "lib",
        permissions: "lrwxrwxrwx",
        path: "/",
        link: 1,
        user: "root",
        group: "root",
        size: 7,
        time: "Jun  9 09:53",
    },
    {
        name: "proc",
        permissions: "dr-xr-xr-x",
        path: "/",
        link: 348,
        user: "root",
        group: "root",
        size: 0,
        time: "",
    },
    {
        name: "root",
        permissions: "drwxr-x---",
        path: "/",
        link: 2,
        user: "root",
        group: "root",
        size: 19,
        time: "Aug  7 10:31",
    },
    {
        name: "run",
        permissions: "drwxr-xr-x",
        path: "/",
        link: 30,
        user: "root",
        group: "root",
        size: 840,
        time: "Aug  7 10:31",
    },
    {
        name: "sbin",
        permissions: "lrwxrwxrwx",
        path: "/",
        link: 1,
        user: "root",
        group: "root",
        size: 7,
        time: "Jun  9 09:53",
    },
    {
        name: "srv",
        permissions: "drwxr-xr-x",
        path: "/",
        link: 4,
        user: "root",
        group: "root",
        size: 4096,
        time: "Jul 29 14:02",
    },
    {
        name: "sys",
        permissions: "dr-xr-xr-x",
        path: "/",
        link: 13,
        user: "root",
        group: "root",
        size: 0,
        time: "Aug  7 10:31",
    },
    {
        name: "tmp",
        permissions: "drwxrwxrwt",
        path: "/",
        link: 14,
        user: "root",
        group: "root",
        size: 380,
        time: "Aug  7 11:15",
    },
    {
        name: "usr",
        permissions: "drwxr-xr-x",
        path: "/",
        link: 9,
        user: "root",
        group: "root",
        size: 4096,
        time: "Aug  7 11:15",
    },
    {
        name: "var",
        permissions: "drwxr-xr-x",
        path: "/",
        link: 12,
        user: "root",
        group: "root",
        size: 4096,
        time: "Aug  5 16:42",
    },
    {
        name: "mnt",
        permissions: "drwxr-xr-x",
        path: "/",
        link: 2,
        user: "root",
        group: "root",
        size: 4096,
        time: "Jun  9 09:53",
    },
]

export default directory