

const file= [
    {
        name:".bash_history",
        permissions:"",
        path: "/home/user",
        text:"",
        link:1,
        user: "",
        group: "",
        size: 0,
        time:"",
    },
    {
        name:".bash_logout",
        permissions:"",
        path: "/home/user",
        text:"",
        link:1,
        user: "",
        group: "",
        size: 0,
        time:"",
    },
    {
        name:".bash_profile",
        permissions:"",
        path: "/home/user",
        text:"",
        link:1,
        user: "",
        group: "",
        size: 0,
        time:"",
    },
    {
        name:".bashrc",
        permissions:"",
        path: "/home/user",
        text:"",
        link:1,
        user: "",
        group: "",
        size: 0,
        time:"",
    },
    {
        name:".cache",
        permissions:"",
        path: "/home/user",
        text:"",
        link:1,
        user: "",
        group: "",
        size: 0,
        time:"",
    },
    {
        name:".config",
        permissions:"",
        path: "/home/user",
        text:"",
        link:1,
        user: "",
        group: "",
        size: 0,
        time:"",
    },
    {

        name:"file.txt",
        permissions:"",
        path: "/home/user",
        text:"hello,how are you \n i am fine and you \n  me too thanks",
        link:1,
        user: "",
        group: "",
        size: 0,
        time:"",
    },
    {

        name:"file1.txt",
        permissions:"",
        path: "/home/user",
        text:"hello,how are you \n i am fine and you \n me too thanks",
        link:1,
        user: "",
        group: "",
        size: 0,
        time:"",
    }
]

export default file