

const file = [
    {
        name: ".bash_history",
        permissions: "-rw-------",
        path: "/home/",
        text: "",
        link: 1,
        user: "",
        group: "",
        size: 5146,
        time: "Aug  7 01:02",
    },
    {
        name: ".bash_logout",
        permissions: "-rw-r--r--",
        path: "/home/",
        text: "",
        link: 1,
        user: "",
        group: "",
        size: 21,
        time: "Jan  9  2022",
    },
    {
        name: ".bash_profile",
        permissions: "-rw-r--r--",
        path: "/home/",
        text: "",
        link: 1,
        user: "",
        group: "",
        size: 57,
        time: "Jan  9  2022",
    },
    {
        name: ".bashrc",
        permissions: "-rw-r--r--",
        path: "/home/",
        text: "",
        link: 1,
        user: "",
        group: "",
        size: 3878,
        time: "Aug  1 00:05",
    },
    {
        name: ".nanorc",
        permissions: "-rw-r--r--",
        path: "/home/",
        text: "",
        link: 1,
        user: "",
        group: "",
        size: 53,
        time: "Jun  3 16:27",
    },
    {

        name: "file.txt",
        permissions: "-rw-r--r--",
        path: "/home/",
        text: "hello,how are you \n i am fine and you \n  me too thanks",
        link: 1,
        user: "",
        group: "",
        size: 0,
        time: "Jun 20 16:27",
    },
    {

        name: "file1.txt",
        permissions: "-rw-r--r--",
        path: "/home/",
        text: "hello,how are you \n i am fine and you \n me too thanks",
        link: 1,
        user: "",
        group: "",
        size: 0,
        time: "Jun 25 16:27",
    }
]

export default file